### ISSUE TITLE
potential issues on Mac OSX

### ISSUE THREAD

**Issue by xrdavies** [XDagger/xdag#97]
dnet fork
==11195==ThreadSanitizer: starting new threads after multi-threaded fork is not supported. Dying (set die_after_fork=0 to override)

**Comment by xrdavies** [comment]
ASAN:DEADLYSIGNAL
=================================================================
==10136==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff539cd105 bp 0x700006045dd0 sp 0x700006045d98 T16777215)
==10136==The signal is caused by a READ memory access.
==10136==Hint: address points to the zero page.
    #0 0x7fff539cd104 in cerror (libsystem_kernel.dylib:x86_64+0x13104)

==10136==Register values:
rax = 0xffffffffffffffff  rbx = 0x0000000000000000  rcx = 0x00007fff539d605a  rdx = 0xffffffffffffffff  
rdi = 0x000000000000003c  rsi = 0x0000000000000000  rbp = 0x0000700006045dd0  rsp = 0x0000700006045d98  
 r8 = 0x0000000000000001   r9 = 0x0000000000000000  r10 = 0x0000000000000001  r11 = 0x0000000000000247  
r12 = 0x00000001005148d0  r13 = 0x0000000000000000  r14 = 0x0000700006045df8  r15 = 0x0000700006045de8  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_kernel.dylib:x86_64+0x13104) in cerror
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.

**Comment by xrdavies** [comment]
ASAN:DEADLYSIGNAL
=================================================================
==17129==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff539cd105 bp 0x700000b29dd0 sp 0x700000b29d98 T16777215)
==17129==The signal is caused by a READ memory access.
==17129==Hint: address points to the zero page.
atos(17130,0x100354340) malloc: enabling scribbling to detect mods to free blocks
    #0 0x7fff539cd104 in cerror (libsystem_kernel.dylib:x86_64+0x13104)

==17129==Register values:
rax = 0xffffffffffffffff  rbx = 0x0000000000000000  rcx = 0x00007fff539d605a  rdx = 0xffffffffffffffff  
rdi = 0x000000000000003c  rsi = 0x0000000000000000  rbp = 0x0000700000b29dd0  rsp = 0x0000700000b29d98  
 r8 = 0x0000000000000001   r9 = 0x0000000000000000  r10 = 0x0000000000000001  r11 = 0x0000000000000247  
r12 = 0x00000001005148d0  r13 = 0x0000000000000000  r14 = 0x0000700000b29df8  r15 = 0x0000700000b29de8  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_kernel.dylib:x86_64+0x13104) in cerror
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.

**Comment by xrdavies** [comment]
==22567==ThreadSanitizer: starting new threads after multi-threaded fork is not supported. Dying (set die_after_fork=0 to override)

**Comment by xrdavies** [comment]
xdag> GuardMalloc[xdag-22612]: attempted free of pointer 0x101195fe0 that was not claimed by any registered malloc zone

**Comment by xrdavies** [comment]
=================================================================
==2085==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x000106e7f820 in thread T16777215
==2085==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.39.2/src/projects/compiler-rt/lib/asan/asan_errors.cc:144 "((free_stack->size)) > ((0))" (0x0, 0x0)
atos(2093,0x100354340) malloc: enabling scribbling to detect mods to free blocks
    #0 0x100524fbf in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x5dfbf)

Warning: hit breakpoint while running function, skipping commands and conditions to prevent recursion.warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
AddressSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.

**Comment by xrdavies** [comment]
xdag client/server, version 0.2.2.
Transport module: dnet T11.231-T13.714.
Password: 123456

ASAN:DEADLYSIGNAL
=================================================================
==8282==ERROR: AddressSanitizer: stack-overflow on address 0x70000c03c000 (pc 0x7fff6eea4da9 bp 0x70000c03aaf0 sp 0x70000c03aaf0 T6)
    #0 0x7fff6eea4da8 in _platform_bzero$VARIANT$Ivybridge (libsystem_platform.dylib:x86_64+0xda8)

SUMMARY: AddressSanitizer: stack-overflow (libsystem_platform.dylib:x86_64+0xda8) in _platform_bzero$VARIANT$Ivybridge
Thread T6 created by T0 here:
    #0 0x1005357a6 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4d7a6)
    #1 0x1000141e3 in xdag_blocks_start block.c:1131
    #2 0x10008a3ff in xdag_init init.c:198
    #3 0x1000f7e53 in main main.c:7
    #4 0x7fff6eb97014 in start (libdyld.dylib:x86_64+0x1014)

2018-05-03 00:57:10.107552+0800 xdag[8282:716950] =================================================================
2018-05-03 00:57:10.107952+0800 xdag[8282:716950] ==8282==ERROR: AddressSanitizer: stack-overflow on address 0x70000c03c000 (pc 0x7fff6eea4da9 bp 0x70000c03aaf0 sp 0x70000c03aaf0 T6)
2018-05-03 00:57:10.108265+0800 xdag[8282:716950]     #0 0x7fff6eea4da8 in _platform_bzero$VARIANT$Ivybridge (libsystem_platform.dylib:x86_64+0xda8)
2018-05-03 00:57:10.108478+0800 xdag[8282:716950] 
2018-05-03 00:57:10.108707+0800 xdag[8282:716950] SUMMARY: AddressSanitizer: stack-overflow (libsystem_platform.dylib:x86_64+0xda8) in _platform_bzero$VARIANT$Ivybridge
2018-05-03 00:57:10.108938+0800 xdag[8282:716950] Thread T6 created by T0 here:
2018-05-03 00:57:10.109184+0800 xdag[8282:716950]     #0 0x1005357a6 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4d7a6)
2018-05-03 00:57:10.115000+0800 xdag[8282:716950]     #1 0x1000141e3 in xdag_blocks_start block.c:1131
2018-05-03 00:57:10.115231+0800 xdag[8282:716950]     #2 0x10008a3ff in xdag_init init.c:198
2018-05-03 00:57:10.115379+0800 xdag[8282:716950]     #3 0x1000f7e53 in main main.c:7
2018-05-03 00:57:10.115510+0800 xdag[8282:716950]     #4 0x7fff6eb97014 in start (libdyld.dylib:x86_64+0x1014)
2018-05-03 00:57:10.115646+0800 xdag[8282:716950] 
2018-05-03 00:57:10.115774+0800 xdag[8282:716950] 
==8282==ABORTING
Program ended with exit code: 5

**Comment by xrdavies** [comment]
xdag> =================================================================
==7937==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0001003a2f00 at pc 0x0001004ff712 bp 0x700000428810 sp 0x700000427fb0
WRITE of size 1 at 0x0001003a2f00 thread T8
atos(7938,0x100357380) malloc: enabling scribbling to detect mods to free blocks
    #0 0x1004ff711 in wrap_memmove (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1b711)

0x0001003a2f00 is located 0 bytes to the right of global variable 'buf' defined in '/Volumes/HD/Development/OpenSource/xdag-1/client/utils/log.c:261:14' (0x10039ef00) of size 16384
SUMMARY: AddressSanitizer: global-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1b711) in wrap_memmove
Shadow bytes around the buggy address:
  0x100020074590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000200745a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000200745b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000200745c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000200745d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1000200745e0:[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1000200745f0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x100020074600: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x100020074610: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x100020074620: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x100020074630: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T8 created by T0 here:
    #0 0x10053299d in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4e99d)
    #1 0x10001406e in xdag_blocks_start block.c:1131
    #2 0x100089d78 in xdag_init init.c:198
    #3 0x1000f7423 in main main.c:7
    #4 0x7fff72d7e014 in start (libdyld.dylib:x86_64+0x1014)

2018-05-06 17:25:22.512588+0800 xdag[7937:1163944] =================================================================
2018-05-06 17:25:22.512922+0800 xdag[7937:1163944] ==7937==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0001003a2f00 at pc 0x0001004ff712 bp 0x700000428810 sp 0x700000427fb0
2018-05-06 17:25:22.513125+0800 xdag[7937:1163944] WRITE of size 1 at 0x0001003a2f00 thread T8
2018-05-06 17:25:22.513328+0800 xdag[7937:1163944]     #0 0x1004ff711 in wrap_memmove (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1b711)
2018-05-06 17:25:22.513657+0800 xdag[7937:1163944] 
2018-05-06 17:25:22.513904+0800 xdag[7937:1163944] 0x0001003a2f00 is located 0 bytes to the right of global variable 'buf' defined in '/Volumes/HD/Development/OpenSource/xdag-1/client/utils/log.c:261:14' (0x10039ef00) of size 16384
2018-05-06 17:25:22.514152+0800 xdag[7937:1163944] SUMMARY: AddressSanitizer: global-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1b711) in wrap_memmove
2018-05-06 17:25:22.514347+0800 xdag[7937:1163944] Shadow bytes around the buggy address:
2018-05-06 17:25:22.514592+0800 xdag[7937:1163944]   0x100020074590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2018-05-06 17:25:22.514834+0800 xdag[7937:1163944]   0x1000200745a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2018-05-06 17:25:22.515005+0800 xdag[7937:1163944]   0x1000200745b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2018-05-06 17:25:22.515194+0800 xdag[7937:1163944]   0x1000200745c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2018-05-06 17:25:22.515385+0800 xdag[7937:1163944]   0x1000200745d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2018-05-06 17:25:22.515631+0800 xdag[7937:1163944] =>0x1000200745e0:[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.515886+0800 xdag[7937:1163944]   0x1000200745f0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.516130+0800 xdag[7937:1163944]   0x100020074600: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.516348+0800 xdag[7937:1163944]   0x100020074610: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.516516+0800 xdag[7937:1163944]   0x100020074620: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.516753+0800 xdag[7937:1163944]   0x100020074630: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
2018-05-06 17:25:22.517017+0800 xdag[7937:1163944] Shadow byte legend (one shadow byte represents 8 application bytes):
2018-05-06 17:25:22.517280+0800 xdag[7937:1163944]   Addressable:           00
2018-05-06 17:25:22.517716+0800 xdag[7937:1163944]   Partially addressable: 01 02 03 04 05 06 07
2018-05-06 17:25:22.517931+0800 xdag[7937:1163944]   Heap left redzone:       fa
2018-05-06 17:25:22.518251+0800 xdag[7937:1163944]   Freed heap region:       fd
2018-05-06 17:25:22.518530+0800 xdag[7937:1163944]   Stack left redzone:      f1
2018-05-06 17:25:22.518740+0800 xdag[7937:1163944]   Stack mid redzone:       f2
2018-05-06 17:25:22.519039+0800 xdag[7937:1163944]   Stack right redzone:     f3
2018-05-06 17:25:22.519319+0800 xdag[7937:1163944]   Stack after return:      f5
2018-05-06 17:25:22.519591+0800 xdag[7937:1163944]   Stack use after scope:   f8
2018-05-06 17:25:22.519853+0800 xdag[7937:1163944]   Global redzone:          f9
2018-05-06 17:25:22.520111+0800 xdag[7937:1163944]   Global init order:       f6
2018-05-06 17:25:22.520358+0800 xdag[7937:1163944]   Poisoned by user:        f7
2018-05-06 17:25:22.520700+0800 xdag[7937:1163944]   Container overflow:      fc
2018-05-06 17:25:22.521017+0800 xdag[7937:1163944]   Array cookie:            ac
2018-05-06 17:25:22.521277+0800 xdag[7937:1163944]   Intra object redzone:    bb
2018-05-06 17:25:22.521477+0800 xdag[7937:1163944]   ASan internal:           fe
2018-05-06 17:25:22.521676+0800 xdag[7937:1163944]   Left alloca redzone:     ca
2018-05-06 17:25:22.521898+0800 xdag[7937:1163944]   Right alloca redzone:    cb
2018-05-06 17:25:22.522311+0800 xdag[7937:1163944] Thread T8 created by T0 here:
2018-05-06 17:25:22.522648+0800 xdag[7937:1163944]     #0 0x10053299d in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4e99d)
2018-05-06 17:25:22.522946+0800 xdag[7937:1163944]     #1 0x10001406e in xdag_blocks_start block.c:1131
2018-05-06 17:25:22.523134+0800 xdag[7937:1163944]     #2 0x100089d78 in xdag_init init.c:198
2018-05-06 17:25:22.523304+0800 xdag[7937:1163944]     #3 0x1000f7423 in main main.c:7
2018-05-06 17:25:22.523485+0800 xdag[7937:1163944]     #4 0x7fff72d7e014 in start (libdyld.dylib:x86_64+0x1014)
2018-05-06 17:25:22.523716+0800 xdag[7937:1163944] 
2018-05-06 17:25:22.523992+0800 xdag[7937:1163944] 
==7937==ABORTING

**Comment by xrdavies** [comment]
2018-09-08 01:04:00.364 [700000c84000:INFO]  Mintop: 0092b077d786ae0c36ba1efd2f7566c299f8d15c7382e3de1334c0ff93e00d9a t=16e4abdffff pos=0
2018-09-08 01:04:00.416 [700000972000:INFO]  MAIN +: c466975da299d6146fe0451a16ee461e1a7778557b355947a8ba33fca822221d t=16e4abcffff pos=0
2018-09-08 01:04:01.233 [700000c01000:INFO]  Nopaid: c3ce5f13cbaae4f74be5aa0d3b17f7a727d8404cba9f25327c0c169340adda4d t=16e4aafffff res=-9
2018-09-08 01:04:31.709 [700000d8a000:INFO]  QueryB: t=16e16500000 dt=100000
2018-09-08 01:05:02.283 [7fffb0968380:FATA]  Signal 11 delivered
2018-09-08 01:05:02.284 [7fffb0968380:FATA]  RIP=7fff7849befb, EFL=10206, ERR=6, CR2=1035867a, 
2018-09-08 01:05:02.284 [7fffb0968380:FATA]  RAX=10357d82, RBX=103, RCX=10000, RDX=e06a0, RSI=203, RDI=7fffb0968358, RBP=7ffee3c966e0, RSP=7ffee3c966d0, 
2018-09-08 01:05:02.284 [7fffb0968380:FATA]  R8=1, R9=7fe19df0f2d0, R10=10cb6a3e0, R11=7fff7849be98, R12=10c227030, R13=1, R14=16, R15=40, 
2018-09-08 01:05:02.285 [7fffb0968380:FATA]  0   xdag                                0x000000010bfa4f3d sigCatch + 2589
2018-09-08 01:05:02.285 [7fffb0968380:FATA]  1   libsystem_platform.dylib            0x00007fff7848ff5a _sigtramp + 26
2018-09-08 01:05:02.285 [7fffb0968380:FATA]  2   ???                                 0x00007ffff4d27f60 0x0 + 140737300823904
2018-09-08 01:05:02.286 [7fffb0968380:FATA]  3   xdag                                0x000000010c104f23 CRYPTO_THREAD_cleanup_local + 12
2018-09-08 01:05:02.286 [7fffb0968380:FATA]  4   xdag                                0x000000010c00bf1b async_deinit + 16
2018-09-08 01:05:02.286 [7fffb0968380:FATA]  5   xdag                                0x000000010c0bb15e OPENSSL_cleanup + 192
2018-09-08 01:05:02.286 [7fffb0968380:FATA]  6   libsystem_c.dylib                   0x00007fff7822def4 __cxa_finalize_ranges + 358
2018-09-08 01:05:02.287 [7fffb0968380:FATA]  7   libsystem_c.dylib                   0x00007fff7822e1fe exit + 55
2018-09-08 01:05:02.287 [7fffb0968380:FATA]  8   libdyld.dylib                       0x00007fff7818101c start + 8
2018-09-08 01:05:02.287 [7fffb0968380:FATA]  9   ???                                 0x0000000000000006 0x0 + 6
2018-09-08 01:05:12.291 [7fffb0968380:MESS]  Initializing log system...
2018-09-08 01:05:12.291 [7fffb0968380:MESS]  Reading hosts database...
2018-09-08 01:05:12.292 [7fffb0968380:MESS]  Initializing cryptography...
